import type { Laptop } from './types'

export const laptops: Laptop[] = [
    {
        id: '1',
        name: 'Dell G15 5530 Gaming Laptop',
        brand: 'Dell',
        category: 'gaming',
        price: 94990,
        originalPrice: 104990,
        discount: 10,
        specs: {
            processor: 'Intel Core i7-13650HX',
            ram: '16GB DDR5',
            storage: '1TB SSD',
            graphics: 'NVIDIA RTX 4060 8GB',
            display: '15.6" FHD 165Hz',
            battery: '86Wh',
        },
        rating: 4.8,
        reviews: 325,
        image: '/products/dell-g15.webp',
        description:
            'A high-performance gaming laptop designed for gamers, developers, designers, and power users.',
        inStock: true,
    },

    {
        id: '2',
        name: 'HP Victus 15',
        brand: 'HP',
        category: 'gaming',
        price: 78990,
        originalPrice: 84990,
        discount: 7,
        specs: {
            processor: 'AMD Ryzen 7 7840HS',
            ram: '16GB DDR5',
            storage: '512GB SSD',
            graphics: 'RTX 4050 6GB',
            display: '15.6" FHD 144Hz',
            battery: '70Wh',
        },
        rating: 4.7,
        reviews: 246,
        image: '/products/hp-victus.webp',
        description:
            'Built for immersive gaming with smooth visuals and reliable Ryzen performance.',
        inStock: true,
    },

    {
        id: '3',
        name: 'Lenovo Legion Pro 5',
        brand: 'Lenovo',
        category: 'gaming',
        price: 139990,
        originalPrice: 149990,
        discount: 7,
        specs: {
            processor: 'Intel Core i9-14900HX',
            ram: '32GB DDR5',
            storage: '1TB SSD',
            graphics: 'RTX 4070',
            display: '16" WQXGA 240Hz',
            battery: '80Wh',
        },
        rating: 4.9,
        reviews: 184,
        image: '/products/lenovo-legion.webp',
        description:
            'Premium gaming laptop with desktop-class performance for creators and gamers.',
        inStock: true,
    },

    {
        id: '4',
        name: 'ASUS ROG Strix G16',
        brand: 'ASUS',
        category: 'gaming',
        price: 164990,
        originalPrice: 179990,
        discount: 8,
        specs: {
            processor: 'Intel Core Ultra 9',
            ram: '32GB DDR5',
            storage: '2TB SSD',
            graphics: 'RTX 4080',
            display: '16" QHD+ 240Hz',
            battery: '90Wh',
        },
        rating: 4.9,
        reviews: 138,
        image: '/products/asus-rog-g16.webp',
        description:
            'Flagship gaming laptop with top-tier graphics and premium cooling.',
        inStock: true,
    },

    {
        id: '5',
        name: 'Apple MacBook Air M3',
        brand: 'Apple',
        category: 'ultrabook',
        price: 114900,
        originalPrice: 124900,
        discount: 8,
        specs: {
            processor: 'Apple M3',
            ram: '16GB Unified Memory',
            storage: '512GB SSD',
            graphics: '10-Core GPU',
            display: '15.3" Liquid Retina',
            battery: '18 Hours',
        },
        rating: 4.9,
        reviews: 528,
        image: '/products/macbook-air-m3.webp',
        description:
            'Ultra-light premium laptop with exceptional battery life and performance.',
        inStock: true,
    },

    {
        id: '6',
        name: 'Dell Inspiron 15',
        brand: 'Dell',
        category: 'student',
        price: 56990,
        originalPrice: 61990,
        discount: 8,
        specs: {
            processor: 'Intel Core i5-1335U',
            ram: '16GB DDR4',
            storage: '512GB SSD',
            graphics: 'Intel Iris Xe',
            display: '15.6" FHD IPS',
            battery: '54Wh',
        },
        rating: 4.6,
        reviews: 498,
        image: '/products/dell-inspiron.webp',
        description:
            'Reliable everyday laptop perfect for students, office work, and coding.',
        inStock: true,
    },

    {
        id: '7',
        name: 'HP 15s Ryzen 5',
        brand: 'HP',
        category: 'student',
        price: 48990,
        originalPrice: 52990,
        discount: 8,
        specs: {
            processor: 'AMD Ryzen 5 7530U',
            ram: '16GB DDR4',
            storage: '512GB SSD',
            graphics: 'AMD Radeon Graphics',
            display: '15.6" FHD',
            battery: '50Wh',
        },
        rating: 4.5,
        reviews: 642,
        image: '/products/hp-15s.webp',
        description:
            'Affordable laptop with excellent multitasking performance and battery life.',
        inStock: true,
    },

    {
        id: '8',
        name: 'Lenovo IdeaPad Slim 5',
        brand: 'Lenovo',
        category: 'business',
        price: 72990,
        originalPrice: 79990,
        discount: 9,
        specs: {
            processor: 'Intel Core Ultra 7',
            ram: '16GB LPDDR5X',
            storage: '1TB SSD',
            graphics: 'Intel Arc',
            display: '14" 2.2K IPS',
            battery: '65Wh',
        },
        rating: 4.8,
        reviews: 221,
        image: '/products/ideapad-slim.webp',
        description:
            'Premium lightweight laptop built for business professionals and productivity.',
        inStock: true,
    },

    {
        id: '9',
        name: 'Acer Nitro V 15',
        brand: 'Acer',
        category: 'gaming',
        price: 82990,
        originalPrice: 89990,
        discount: 8,
        specs: {
            processor: 'Intel Core i7-13620H',
            ram: '16GB DDR5',
            storage: '512GB SSD',
            graphics: 'RTX 4050',
            display: '15.6" FHD 144Hz',
            battery: '57Wh',
        },
        rating: 4.6,
        reviews: 267,
        image: '/products/acer-nitro.webp',
        description:
            'Powerful gaming laptop with RTX graphics for smooth gameplay and productivity.',
        inStock: true,
    },

    {
        id: '10',
        name: 'MSI Katana 15',
        brand: 'MSI',
        category: 'gaming',
        price: 124990,
        originalPrice: 134990,
        discount: 7,
        specs: {
            processor: 'Intel Core i7-14650HX',
            ram: '16GB DDR5',
            storage: '1TB SSD',
            graphics: 'RTX 4070',
            display: '15.6" QHD 165Hz',
            battery: '75Wh',
        },
        rating: 4.8,
        reviews: 194,
        image: '/products/msi-katana.webp',
        description:
            'High-performance gaming laptop engineered for competitive gaming and creative workflows.',
        inStock: true,
    },
]